---
name: "string_to_code action"
description: "Github action calling string_to_code"
author: "Piotr Idzik"
branding:
  icon: "activity"
  color: "black"
inputs:
  targetLanguage:
    description: "Language of the generater code"
    required: false
    default: ""
  inputStr:
    description: "The string which should be displayed by the generated program"
    required: true
  outputFile:
    description: "The file with generated code"
    required: false
    default: "out.txt"
outputs:
  targetLanguage:
    description: "Language of the generater code"
  code:
    description: "The generated code"
runs:
  using: "docker"
  image: "Dockerfile"
...
