---
name: action_test_bash

'on':
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '36 6 * * *'

permissions:
  contents: read

env:
  INPUT_STR: "Hello, World! (with bash)"
  TARGET_LANGUAGE: bash
  OUTPUT_FILE: "out.sh"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run action
        id: run_action
        uses: ./
        with:
          targetLanguage: ${{ env.TARGET_LANGUAGE }}
          inputStr: ${{ env.INPUT_STR }}
          outputFile: ${{ env.OUTPUT_FILE }}

      - name: Check targetLanguage
        run: |
          test "${{ steps.run_action.outputs.targetLanguage }}" == "${{ env.TARGET_LANGUAGE }}"

      - name: Check output code
        run: |
          sudo chmod +x "${{ env.OUTPUT_FILE }}"
          test "$(./"${{ env.OUTPUT_FILE }}")" == "${{ env.INPUT_STR }}"
...
