---
name: action_test

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run action
        id: run_action
        uses: ./
        with:
          targetLanguage: python3
          inputStr: "Hello, World!"
          outputFile: "out.txt"

      - name: Check targetLanguage
        run: |
          test "${{ steps.run_action.outputs.targetLanguage }}" == "python3"

      - name: Check output code 
        run: |
          test "$(python3 out.txt)" == "Hello, World!"
...
