---
name: all_url_check

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '3 3,15 * * *'

jobs:
  run_lychee:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: link_check with lychee-action
        id: link_check
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: >
           --verbose
           --no-progress
           **/*.md
          fail: true
...
